- .github/workflows/ci.yml
> ci: Better settings

- .dockerignore
- .github/workflows/ci.yml
- .github/workflows/docker.yml
- .gitignore
- Dockerfile
- README.md
- distribution/pom.xml
> build(docker): Native image and CI

- Dockerfile
- Dockerfile.native
- README.md
- distribution/commandline/pom.xml
- distribution/commandline/src/assemble/bin.xml
> build: debian:bookworm-slim for native and improve commandline packaging

- hawkeye-core/pom.xml
- hawkeye-core/src/main/java/io/korandoru/hawkeye/core/FileContent.java
- hawkeye-core/src/main/java/io/korandoru/hawkeye/core/HeaderSource.java
- hawkeye-core/src/main/java/io/korandoru/hawkeye/core/LiteralHeaderSource.java
- hawkeye-core/src/main/java/io/korandoru/hawkeye/core/UrlHeaderSource.java
- hawkeye-core/src/test/java/io/korandoru/hawkeye/core/HeaderSourceTest.java
- hawkeye-core/src/test/resources/single-line-header.txt
> feat: Add HeaderSource

- distribution/action/action.yml
> fix: Action docker image url

- .github/workflows/ci.yml
> ci: action should keep up-to-date

- hawkeye-core/src/main/java/io/korandoru/hawkeye/core/document/DocumentType.java
- hawkeye-core/src/main/java/io/korandoru/hawkeye/core/header/HeaderType.java
> feat: Add Rust file support and update some predefinitions

- distribution/commandline/src/embeddedLaunchScript.sh
> chore: cleanup launch script

- hawkeye-core/src/main/java/io/korandoru/hawkeye/core/HawkEyeConfig.java
- hawkeye-core/src/main/java/io/korandoru/hawkeye/core/LicenseProcessor.java
- hawkeye-core/src/main/resources/META-INF/native-image/hawkeye-core/reflect-config.json
- licenserc.toml
> fix: Manually add Java7HandlersImpl in reflect-config

- README.md
- hawkeye-core/src/main/java/io/korandoru/hawkeye/core/LicenseProcessor.java
- hawkeye-core/src/main/java/io/korandoru/hawkeye/core/config/ConfigFileModel.java
- hawkeye-core/src/main/java/io/korandoru/hawkeye/core/config/HawkEyeConfig.java
- hawkeye-core/src/main/java/io/korandoru/hawkeye/core/config/HeaderStyleModel.java
- hawkeye-core/src/main/java/io/korandoru/hawkeye/core/config/HeaderStylesModel.java
- hawkeye-core/src/main/java/io/korandoru/hawkeye/core/config/LicenseRCModel.java
- hawkeye-core/src/main/resources/META-INF/native-image/hawkeye-core/reflect-config.json
> feat: user-defined header style

- README.md
> docs: modify files in container requires run as owner

- .github/workflows/ci.yml
- .github/workflows/release.yml
> ci: Use docker buildx

- README.md
Signed-off-by: suyanhanx <suyanhanx@gmail.com>
> docs: append commands to readme

- .github/workflows/ci.yml
> ci: add maven cache

- hawkeye-core/src/main/resources/META-INF/native-image/io.korandoru.hawkeye/hawkeye-core/reflect-config.json
- pom.xml
This closes https://github.com/korandoru/hawkeye/issues/82.
> build(deps): Upgrade Jackson version to 2.15.2

- Dockerfile.native
- README.md
- hawkeye-native/pom.xml
Related to https://github.com/oracle/graal/issues/5872
> build: native image use apline musl

- .github/workflows/ci.yml
- Cargo.toml
- cli/src/main.rs
- fmt/src/document/mod.rs
- fmt/src/header/parser.rs
- fmt/src/lib.rs
- fmt/src/selection.rs
- fmt/tests/tests.rs
- rust-toolchain.toml
> refactor: remove unstable Rust features

- README.md
> docs: how to install prebuilt binary

- fmt/src/license/mod.rs
> refactor: clarify how HeaderSource loaded

- cli/src/cli.rs
- fmt/src/processor.rs
- fmt/src/selection.rs
- tests/it.py
This closes https://github.com/korandoru/hawkeye/issues/139.
> feat: ignore header path if present

- .github/workflows/docker.yml
> revert: "ci: use matrix build for multi-arch build"

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/build.rs
- fmt/Cargo.toml
- fmt/src/document/factory.rs
This closes https://github.com/korandoru/hawkeye/issues/160.
> ci: guard MSRV build 1.76.0

- fmt/src/document/defaults.toml
Thank you for hawkeye. This PR adds support for .svelte files. ([Svelte](https://svelte.dev/docs/svelte/overview) is a framework for building user interfaces on the web).
> feat: add support for .svelte extension
