Dockerfile.native
=> build(docker): Replace ubuntu:jammy with graalvm-native-image-base

Dockerfile.native
We have renamed the Chainguard image, so this PR is to reflect the new name.
The old name should still be available for some time, but will not be receiving updates anymore.
https://github.com/chainguard-images/images/tree/main/images/graalvm-native
cc @tisonkun
=> build(docker): Use new name for GraalVM base image

hawkeye-core/src/test/java/io/korandoru/hawkeye/core/SelectionTest.java
This closes #57.
The functionality may be fixed by #61.
=> test: add testContainsEmoji

hawkeye-core/src/main/java/io/korandoru/hawkeye/core/config/ConfigFileModel.java
* `keywords` otherwise fail if specified;
* `mapping` otherwise null if not specified.
=> fix: annontate for fields with default value

README.md
This closes https://github.com/korandoru/hawkeye/issues/90.
=> docs: add basic usage doc for hawkeye-maven-plugin

README.md, hawkeye-core/src/main/java/io/korandoru/hawkeye/core/config/HawkEyeConfig.java, hawkeye-maven-plugin/README.md, hawkeye-maven-plugin/pom.xml, hawkeye-maven-plugin/src/main/java/io/korandoru/hawkeye/maven/plugin/AbstractMojo.java, hawkeye-maven-plugin/src/main/java/io/korandoru/hawkeye/maven/plugin/CheckMojo.java, hawkeye-maven-plugin/src/main/java/io/korandoru/hawkeye/maven/plugin/FormatMojo.java, hawkeye-maven-plugin/src/main/java/io/korandoru/hawkeye/maven/plugin/RemoveMojo.java, hawkeye-maven-plugin/src/test/java/io/korandoru/hawkeye/maven/plugin/CheckMojoTest.java, hawkeye-maven-plugin/src/test/java/io/korandoru/hawkeye/maven/plugin/FormatMojoTest.java, hawkeye-maven-plugin/src/test/java/io/korandoru/hawkeye/maven/plugin/RemoveMojoTest.java, hawkeye-maven-plugin/src/test/resources/t1.toml, hawkeye-maven-plugin/src/test/resources/t2.toml, pom.xml
This closes https://github.com/korandoru/hawkeye/issues/94.
But not exactly, cause Maven plugin inheritance (under multi-module project) is far more complicated then I ever think of.
For example, this patch works well if you configure the plugin in the parent module and run `mvn hawkeye:check`. But what if you want to bind it with VERIFY phase? The plugin will be inherited into all of the children modules and they will resolve relative path incorrectly. (Although we can support `skip` and skip at all the children modules as we do for the exec goal under the root pom.xml file in this project.)
We should spend some time to investigate what is the proper best practice here. And this PR serves as a reference instead of a mergeable patch.
cc @spencercjh
=> feat(maven): improve experience for multimodule project

hawkeye-core/src/main/java/io/korandoru/hawkeye/core/GitHelper.java
```
java.lang.Exception: git check-ignore failed:
```
For exit code 1 - None of the provided paths are ignored.
```
java.lang.Exception: git check-ignore failed with code 128:
fatal: pathspec 'rust/protos/meta_event.proto' is beyond a symbolic link
```
For cannot follow symlinks.
=> fix: git check-ignore cannot follow symlinks

hawkeye-core/src/main/java/io/korandoru/hawkeye/core/GitHelper.java, hawkeye-core/src/main/java/io/korandoru/hawkeye/core/Selection.java
1. if the link is within baseDir, we should check it in other paths anyway;
2. if the link is outside baseDir, we should not check it.
=> fix: skip symbol links

hawkeye-core/src/main/java/io/korandoru/hawkeye/core/header/HeaderParser.java, hawkeye-core/src/test/data/issue-110/.gitignore, hawkeye-core/src/test/data/issue-110/licenserc.toml, hawkeye-core/src/test/data/issue-110/main.rs, hawkeye-core/src/test/data/issue-110/main.rs.formatted.expected, hawkeye-core/src/test/java/io/korandoru/hawkeye/core/RegressionTest.java, licenserc.toml
This closes #110.
cc @tanruixiang @spencercjh
=> fix: heuristic find header - blank lines after first comments should terminate

Cargo.lock, Dockerfile, README.md, action.yml, fmt/Cargo.toml, fmt/src/error.rs, fmt/src/git.rs, fmt/src/selection.rs
@Byron Thanks a lot for pointing me that we can check ignore with gix.
I'm still investigating how to get the `Platform` struct but draft here for further conversation.
Said we'd like to call `AttributeStack::at_path` and then `Platform::is_excluded`. The first lacking thing is how to get Attribute. I found:
```rust
impl Repository {
pub fn attributes(
&self,
index: &State,
attributes_source: Source,
ignore_source: Source,
exclude_overrides: Option<Search>
) -> Result<AttributeStack<'_>, Error> { ... }
}
```
I can get a repository now, but have no ideas on the other params.
Also some issues I ever encountered with git2:
* Repository is not owned by this user; often happen with Docker on CI. Hopefully we don't have to check the permission ..
=> refactor: migrate git2 to gix

fmt/src/document/defaults.toml
HI! 
Recently I have been focusing on a new programming language called Moonbit. It seems that moonbit's repository also needs a github action to check license header.
I happened to remember today that hawkeye was used in the greptime repository. So I just gave it a try.
Unfortunately, it seems that hawkeye currently does not know how to handle the moonbit code.
=> feat: support `.mbt` extension for moonbit language

Cargo.lock, fmt/Cargo.toml, fmt/src/error.rs, fmt/src/git.rs, fmt/src/selection.rs
This enables far-better performance.
Fixes #123
I didn't actually test performance, and don't know how much tests would catch.
=> refactor: avoid the GitHelper and instead keep data on the stack

fmt/src/license/mod.rs, fmt/src/processor.rs, tests/it.py, tests/load_header_path/license.txt, tests/load_header_path/licenserc.toml
cc @madelaney
This refers to https://github.com/korandoru/hawkeye/discussions/135.
Actually in the previous Java version, we can use resources path for predefined license header. And Discussion-135 is a good predefined BSD 3 Clause template. I'm thinking how we can build a proper bundled licenses loading logic instead of current:
```rust
pub fn bundled_headers(name: &str) -> Option<HeaderSource> {
match name {
"Apache-2.0.txt" => Some(HeaderSource {
content: include_str!("Apache-2.0.txt").to_string(),
}),
"Apache-2.0-ASF.txt" => Some(HeaderSource {
content: include_str!("Apache-2.0-ASF.txt").to_string(),
}),
_ => None,
}
}
```
Or we can actually just append it ...
=> fix: real header path should load

cli/src/cli.rs
Hi there! I found that a log containing errors can stop the Github action. However, the actions format and remove should not be treated as errors since they're intended by the users.
=> refactor(logging): replace error! by info! in the actions of format and remove

fmt/src/document/factory.rs, fmt/src/git.rs
Follow up @Byron's suggestion at https://github.com/korandoru/hawkeye/pull/150/files#r1634220929.
=> fix: always use path when handling path logics

fmt/src/document/defaults.toml
Hi there, great project you have here, it's really handy thanks.
I ran it against one of my repositories, and it was able to add headers for `.js`, `.ts` and `.tsx` files, but not `.jsx` files.
With the change in this PR, `.jsx` files get headers inserted in the same way as `.tsx` files.
I've tested it locally (via docker) and it works as intended.
Would be great to have this merged & released so I can update my Github action to also enforce this on JSX files.
Thanks again for this project, it's great
=> feat: Add support for `.jsx` files

.github/workflows/docker.yml
This simplifies your @actions config by replacing duplication with a matrix configuration.
=> ci: use matrix build for multi-arch build

fmt/src/document/defaults.toml, fmt/src/header/defaults.toml
This change adds support for the `LINE_BLOCK_STYLE` license comment format, and applies it to `*.pkl` and `PklProject` files.
Structure
---------
The comment style is consistent with that of the Pkl project itself:
```
//===----------------------------------------------------------------------===//
// Copyright goes here.
//
// Lorem ipsum dolor sit amet.
//===----------------------------------------------------------------------===//
```
See: https://github.com/apple/pkl/blob/44fd680/stdlib/base.pkl
=> feat: Support Pkl language

fmt/src/config/mod.rs
This refers to https://github.com/korandoru/hawkeye/issues/175 where we can improve the error report as:
```
thread 'main' panicked at cli/src/subcommand.rs:106:52:
called `Result::unwrap()` on an `Err` value: cannot parse config file: licenserc.toml
Caused by:
TOML parse error at line 39, column 2
|
39 | [mappings.LINE]
|  ^^^^^^^^
unknown field `mappings`, expected one of `baseDir`, `inlineHeader`, `headerPath`, `strictCheck`, `useDefaultExcludes`, `useDefaultMapping`, `keywords`, `includes`, `excludes`, `properties`, `mapping`, `git`, `additionalHeaders`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Instead of silicently ignore unknown fields.
=> chore: improve unknown fields error report

fmt/src/document/defaults.toml
Hey, thanks for this nice tool. I would like to use it for Vue files as well as Containerfiles. Therefore I added the configuration for both these types in `defaults.toml`. As I am not that familiar with Rust I am not sure whether this is sufficient. Feel free to correct this.
=> feat: update defaults - add Vue, add Containerfile

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/subcommand.rs, fmt/Cargo.toml, fmt/src/document/factory.rs, fmt/src/header/parser.rs
cc @pstoeckle You can try out this patch by checking out to the branch and run `cargo install --path cli`. Now you have a `hawkeye` executable built upon this branch.
This closes #190
=> feat: flag to store list of files to change
